### ISSUE TITLE
Epic: HfLA: Summer 2025 Potluck

### ISSUE THREAD

**Issue by Rabia2219** [civictechstructure/party#18]
### Overview
We need to have an list of action items so that we can prepare to announce the 2025 Summer Potluck Picnic on Meetup, LinkedIn and Slack
### Action Items
- [x] #23
- [x] #24
- [x] #25
- [x] #41 
- [x] #40
- [x] #32
- [x] #26
- [x] #30
- [x] #31
- [x] #27
- [x] #28
- [x] #29
- [x] #33
- [x] #34
- [x] #36
- [ ] #35
- [x] #44 
- [x] #43 
- [x] #48 
- [x] #47
- [x] #52 
- [x] #45 
- [x] #49
- [x] #50 
- [x] #53 
- [x] #51 
- [x] #46
- [ ] #37
- [ ] #38
   - [ ] Add overview
   - [ ] Add link to Epic template
- [ ] #39

### Resources/Instructions
- [HfLA: Party Committee Interest Form](https://docs.google.com/forms/d/1vq594W0O9Jp9wu_KSdLhK8iugdun6JPRhQmZDkq7o1M/edit)
- [HfLA: Party Committee Interest Form (Responses)](https://docs.google.com/spreadsheets/d/1csbvDzBtw046GSqccPuWLXiOMMfGB_fH5V3-wWjbwYw/edit)
- [HfLA Party Committee Roster](https://docs.google.com/spreadsheets/d/1ZteYPjqI2uJolGM1pDEIm-3G4BS8D5FqVFRkzDdf4KI/edit)
- [Folder with permit application](https://drive.google.com/drive/folders/1MqIUOPmwDm6NFOjsm3MT9_SdC4y6Kqef)
- [people are bringing](https://docs.google.com/spreadsheets/d/1jFHjodvShpxBG7elT31XNqW-t3857xjcx45ueHuDyeY/edit?resourcekey=&gid=1785428508#gid=1785428508)
- [Edit the contribution form](https://docs.google.com/forms/d/1LF5njL0jArWHg9cA4IWsjVXsMd6_WXrgUwBJf1U_clo/edit)
- [contribution form](https://docs.google.com/forms/d/e/1FAIpQLScZ2Ce8s5UumrWZvM3RMv7nehHsfDC7EhNuJLGu4pYC6-Mcqg/viewform)
- Events on meetup
   - [2025 Potluck Picnic](https://www.meetup.com/hackforla/events/302274209/)
   - [2024 Potluck Picnic](https://www.meetup.com/hackforla/events/301856645/)
- [Party WIKI](https://github.com/civictechstructure/party/wiki)
- [Alphabetical list of cities for California and Southern California](https://www.landsmart.com/index.php?option=com_content&view=article&id=161&Itemid=113)

**Comment by Rabia2219** [comment]
#### Links
- [people are bringing](https://docs.google.com/spreadsheets/d/1jFHjodvShpxBG7elT31XNqW-t3857xjcx45ueHuDyeY/edit?resourcekey=&gid=1785428508#gid=1785428508)
- [Edit the contribution form](https://docs.google.com/forms/d/1LF5njL0jArWHg9cA4IWsjVXsMd6_WXrgUwBJf1U_clo/edit)
- [contribution form](https://docs.google.com/forms/d/e/1FAIpQLScZ2Ce8s5UumrWZvM3RMv7nehHsfDC7EhNuJLGu4pYC6-Mcqg/viewform)

**Comment by Rabia2219** [comment]
#### Steps

- after we lock it down, update https://www.meetup.com/hackforla/events/302274209/
  - add image
  - add location
  - update the paragraph 'What to bring' to add new links to 'what people are bringing' and 'contribution form'
  - link to WIKI

**Comment by Rabia2219** [comment]
#### LinkedIn Post Language

🌞 Hack for LA Members only 2025 Summer Potluck Picnic! 🌞

Address: 2459 Motor Ave, Los Angeles, California, US, 90064

Venue: Picnic Area 2

Event Link: https://www.meetup.com/hackforla/events/302274209

Description:
Follow the event link to see details and register on MeetUp.

What do you want to talk about?
Hack for LA's 2024 Member Potluck Picnic was so much fun, we are already planning for 2025! Follow the link to register on Meetup if you are a current or former volunteer.

**Comment by ExperimentsInHonesty** [comment]
If the event is being held at Cheviot Hills, post the following on the bottom of the meetup
```
*Please read [Cheviot Hills Recreation Center Regulations](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Regulations)
```

**Comment by ExperimentsInHonesty** [comment]
# Draft for event

Join us for a fun-filled summer potluck picnic in the park! Hack for LA members and their friends, families, and well-behaved pets are all welcome to attend (dogs must be leashed)*. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

### Mark Your Calendar
📅 Date: July 12th, 2025
🕒 Time: 12 PM - 3 PM PST
📍 Location: TBD

### What to Bring:
Food & Drinks*: Please bring your favorite dish and beverages to share. To help us organize the event better, please check out what other [people are brining](https://docs.google.com/spreadsheets/d/1jFHjodvShpxBG7elT31XNqW-t3857xjcx45ueHuDyeY/preview) and then fill out the [contribution form](https://docs.google.com/forms/d/e/1FAIpQLScZ2Ce8s5UumrWZvM3RMv7nehHsfDC7EhNuJLGu4pYC6-Mcqg/viewform) with the items you plan to bring. This will help avoid duplicates and ensure we have a variety of food and drinks. If you can't bring anything we have an option for that on the contribution form.

Games & Activities*: Feel free to bring any games or activities you'd like to enjoy with others.

### Let Us Know You're Coming
Come out, have fun, and connect with fellow Hack for LA members. We look forward to seeing you there!

✅ RSVP now to this meetup.

### Not a Member Yet of Hack for LA?
Our party is only open to current and former volunteers. We would love to see you at the winter holiday party later this year. If you are interested in volunteering with us, we encourage you to attend our one of our upcoming [Hack for LA Info and Onboarding](https://meetup.com/hackforla/events) meetups.

**Comment by ExperimentsInHonesty** [comment]
# Draft for event

Join us for a fun-filled summer potluck picnic in the park! Hack for LA volunteers (past and present) and their friends, families, and well-behaved pets are all welcome to attend (dogs must be leashed)*. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

### Step 1 - RSVP
✅ RSVP now to this meetup.

### Step 2 - Mark Your Calendar
📅 Date: July 12th, 2025
🕒 Time: 12 PM - 3 PM PST
📍 Location: TBD

### Step 3 - Check out what other [people are brining](https://docs.google.com/spreadsheets/d/1jFHjodvShpxBG7elT31XNqW-t3857xjcx45ueHuDyeY/preview)

### Step 4 - Fill out the [contribution form](https://docs.google.com/forms/d/e/1FAIpQLScZ2Ce8s5UumrWZvM3RMv7nehHsfDC7EhNuJLGu4pYC6-Mcqg/viewform) with the items you plan to bring. 
This will help avoid duplicates and ensure we have a variety of food and drinks. If you can't bring anything, we have an option for that on the contribution form.

Also, feel free to bring any games or activities you'd like to enjoy with others.

### Not a Hack for LA Volunteer Yet?
Our party is only open to current and former volunteers. If you are seeing this invite in June after our last onboarding, we would love to see you at the winter holiday party later this year. If you are interested in volunteering with us, we encourage you to attend our one of our upcoming [Hack for LA Info and Onboarding](https://meetup.com/hackforla/events) meetups.

**Comment by Rabia2219** [comment]
#### Issues to be made for tasks

- [ ] HfLA: Summer 2025 Potluck: Fill and send permit
- [ ] HfLA: Summer 2025 Potluck: Create invite image for 
   - [ ] Contribution Form Header
   - [ ] Meetup Invite
   - [ ] LinkedIn Invite
- [ ] HfLA: Summer 2025 Potluck: Create Meetup Invite
- [ ] HfLA: Summer 2025 Potluck: Create LinkedIn Invite
- [ ] HfLA: Summer 2025 Potluck: Create Slack Invite
- [ ] HfLA: Summer 2025 Potluck: Create Contribution Form
- [ ] HfLA: Summer 2025 Potluck: Create Contribution Form Responses
- [ ] HfLA: Summer 2025 Potluck: Update WIKI page
- [ ] HfLA: Summer 2025 Potluck: Post on Meetup
- [ ] HfLA: Summer 2025 Potluck: Post on LinkedIn
- [ ] HfLA: Summer 2025 Potluck: Post on Slack
- [ ] HfLA: Summer 2025 Potluck: Invite People on LinkedIn from Southern California
- [ ] HfLA: Summer 2025 Potluck: Turn all issues into templates for future years
   - [ ] Update Readme
       - [ ] Add overview
       - [ ] Add link to Epic template

**Comment by Rabia2219** [comment]
### Overview
We need to have an list of action items so that we can prepare to announce the 2025 Summer Potluck Picnic on Meetup, LinkedIn and Slack
### Action Items
- [x] email contact at park on January 2nd to ask for availability for July 12th 2025
- [ ] once availability is confirmed, fill permit application
- [ ] send the permit application back to contact
- [ ] once we have the permit
  - [ ] update contribution form sheet 1 with image from invite
  - [ ] update the contribution form header with new image
  - [ ] update meetup event
     - [ ] add image
     - [ ] add location
        - if the same as last year
           - [ ] add
              ```
              📍 Location: Cheviot Hills Recreation Area, Los Angeles (Picnic Area 2)
              🗺️ [Maps, pictures and other details](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Directions,-Parking-info-and-Pictures)
              ``` 
           - [ ] add after the last paragraph
              ```
              *Please read [Cheviot Hills Recreation Center Regulations](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Regulations)
              ```
  - [ ] create LinkedIn post
     - [ ] invite people on LinkedIn from southern california
- [ ] send thank you emails to people who donated from team@hackforla.org. Templates etc. can be found [here](https://drive.google.com/drive/folders/19hnpM9huWVELcqhS0DgjTYzPsmDLDSsX).

### Resources/Instructions
- [Folder with permit application](https://drive.google.com/drive/folders/1MqIUOPmwDm6NFOjsm3MT9_SdC4y6Kqef)
- [people are bringing](https://docs.google.com/spreadsheets/d/1jFHjodvShpxBG7elT31XNqW-t3857xjcx45ueHuDyeY/edit?resourcekey=&gid=1785428508#gid=1785428508)
- [Edit the contribution form](https://docs.google.com/forms/d/1LF5njL0jArWHg9cA4IWsjVXsMd6_WXrgUwBJf1U_clo/edit)
- [contribution form](https://docs.google.com/forms/d/e/1FAIpQLScZ2Ce8s5UumrWZvM3RMv7nehHsfDC7EhNuJLGu4pYC6-Mcqg/viewform)
- Events on meetup
   - [2025 Potluck Picnic](https://www.meetup.com/hackforla/events/302274209/)
   - [2024 Potluck Picnic](https://www.meetup.com/hackforla/events/301856645/)
- [Party WIKI](https://github.com/civictechstructure/party/wiki)
- [Alphabetical list of cities for California and Southern California](https://www.landsmart.com/index.php?option=com_content&view=article&id=161&Itemid=113)

**Comment by Rabia2219** [comment]
#### Notes

- add steps to creating a new Slack channel for volunteers
- add steps to reaching out for kickoff meeting
- add steps to creating meeting(s) for virtual volunteers

**Comment by Rabia2219** [comment]
#### Notes
- Prior to the kickoff meeting 
   - created a new Slack channel for volunteers
   - reached out for kickoff meeting
   - created meeting(s) for virtual volunteers
- During the kickoff meeting
   - created teams
   - added members to both read and write teams
   - created project boards
   - added issues to project board
   - added members Figma
   - added members to drive
   - created a roster for members
   - gave access members to LinkedIn
 - Tasks
   - [x] create an issue to onboard members to all resources needed
   - [ ] review how to handle the Interest form for each year

**Comment by ExperimentsInHonesty** [comment]
Create new issue
- weekly label check

```
- [ ] [season](https://github.com/civictechstructure/party/issues?q=is%3Aissue%20-label%3A%22season%3A%20summer%22%20-label%3A%22season%3A%20winter%22%20-label%3A%22season%3A%20all%22)
- [ ] [year](https://github.com/civictechstructure/party/issues?q=is%3Aissue%20state%3Aopen%20-label%3A%22year%3A%202022%22%20-label%3A%22year%3A%202023%22%20-label%3A%22year%3A%202024%22%20-label%3A%22year%3A%202025%22%20-label%3A%22year%3A%202026%22%20-label%3A%22year%3A%20all%22)
```
